from DoublyLinkedList import DoublyLinkedList  # Node.py에서 Node 클래스를 가져옴

# insert_back(O(1))
if __name__ == "__main__":
    doublylinkedList = DoublyLinkedList()
    doublylinkedList.insert_back(4)
    doublylinkedList.insert_back(3)
    doublylinkedList.insert_back(2)
    doublylinkedList.insert_back(1)
    print('doublylinkedList.get(0)', doublylinkedList.get(0))
    print('doublylinkedList.get(1)', doublylinkedList.get(1))
    print('doublylinkedList.get(2)', doublylinkedList.get(2))
    print('doublylinkedList.get(3)', doublylinkedList.get(3))
    doublylinkedList.insert_at(0, 100)
    print('=======================================')
    print('doublylinkedList.get(0)', doublylinkedList.get(0))
    print('doublylinkedList.get(1)', doublylinkedList.get(1))
    print('doublylinkedList.get(2)', doublylinkedList.get(2))
    print('doublylinkedList.get(3)', doublylinkedList.get(3))
    print('doublylinkedList.get(4)', doublylinkedList.get(4))
    doublylinkedList.delete(4)
    print('=======================================')
    print('doublylinkedList.get(0)', doublylinkedList.get(0))
    print('doublylinkedList.get(1)', doublylinkedList.get(1))
    print('doublylinkedList.get(2)', doublylinkedList.get(2))
    print('doublylinkedList.get(3)', doublylinkedList.get(3))